- name: Demo on Vars
  hosts: localhost
  #If we declare variables here(play level) all the tasks can access them
  vars:
    URL:  play.google.com
  tasks:
    - name: PrintPlay level variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

  roles:
    - demo