- name: Demo on Vars
  hosts: localhost
  #If we declare variables here(play level) all the tasks can access them
  vars:
    URL:  play.google.com
  tasks:
    - name: PrintPlay level variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
    - name: Print Variables declared inside a task
      vars:
        URL: task.google.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}

  roles:
    - demo
    -
# When the value is starting with variable then we need to double quote

#      ansible.builtin.debug:
#        msg: URL = {{ URL }}  #this value is not starting with variable and hence no need of quotes

#ansible.builtin.debug:
##        msg: URL = {{ URL }} # This value is starting with variable and hence need either single or
#         double quotes