- name: Demo On Loops
  hosts: localhost
  tasks:
    - name: Loop Demo
      ansible.builtin.debug:
        msg: Hello, {{ item }}
      loop:
        - Suprabath
        - saketha
        - Mahanya

    - name: Loop Demo on Maps
      ansible.builtin.debug:
        msg: Hello, {{ item.name  }}, your age is {{ item.age }}
      loop:
        - {name: "Suprabath" , age: 30} #Json inputs
        - {name: "saketha", age: 29}
        - {name: "Mahanya", age: 2}