- name: Demo on handlers
  hosts: localhost
  tasks:
    - name: Copy a sample file
      ansible.builtin.template:
        src: sample.txt
        dest: /tmp/sammple.txt


  handlers:
    - name: Say Hello again
      ansible.builtin.debug:
        msg: hello {{ name }}